harbour-storeman/qml/cover/CoverPage.qml
harbour-storeman/qml/harbour-storeman.qml

What about adding search action to the cover like the jolla store has?

search cover action added

---

rpm/harbour-storeman.spec

See https://github.com/mentaljam/harbour-storeman/commit/c9f31527061f7832cb47f11a9e0003e103dcf5d7#commitcomment-43007118

Revert "version"-define and "constify" the required / displayed version

---

rpm/harbour-storeman.changes
rpm/harbour-storeman.spec

- Fix issue #157
- ssu & rm -f always return 0
- Switch http://repo.merproject.org -> https://repo.sailfishos.org
- Increase version number

storeman.spec: Do not assign repo in global section

---

harbour-storeman.pro

… missed in PR #171 or / and PR #172.

harbour-storeman.pro: Delete repo config file entry

---

src/ornpm.cpp

ornpm.cpp L28: storemanRepo "mentaljam-obs"→"harbour-storeman-obs"

---

rpm/harbour-storeman.spec

Closes #166 and supersedes #214.

spec file: Add SailfishOS:Chum metadata

---

rpm/harbour-storeman.spec

See https://github.com/storeman-developers/harbour-storeman/issues/160 .

spec file (sfos4.2): sailfish-version >= 4.2.0

---

rpm/harbour-storeman.spec

Reverts storeman-developers/harbour-storeman#222

Revert "spec file (sfos3.3): sailfish-version >= 3.3.0 < 4.2.0"

---

rpm/harbour-storeman.spec

Reverts storeman-developers/harbour-storeman#223

Revert "spec file (sfos4.2): sailfish-version >= 4.2.0"

---

rpm/harbour-storeman.spec

Reverts storeman-developers/harbour-storeman#221

Revert "spec file (sfos3.2): sailfish-version >= 3.1.0 < 3.3.0"

---

rpm/harbour-storeman.spec

… with https://github.com/storeman-developers , plus comments for the release branches and the SFOS releases they cover.

spec file: Add categories, comment and unify spelling

---

rpm/harbour-storeman.spec

Reverts storeman-developers/harbour-storeman#252

Revert "spec file: Post release version increase"

---

.github/workflows/build-sfos3.3.yml

Update branch `sfos3.3` from `master` for 0.3.0-3
- build-sfos3.3.yml: Fix copyo (#261) (#262)
- Version-release = 0.3.0-3 (#267)
- Merge pull request #268 from storeman-developers/devel

Update branch `sfos3.3` from `master` for 0.3.0-3

---

.github/workflows/build-sfos3.3.yml

Update branch `sfos4.2` from `master` for 0.3.0-3
- build-sfos3.3.yml: Fix copyo (#261) (#262)
- Version-release = 0.3.0-3 (#267)
- Update `master` from `devel` for 0.3.0-3 (#268)

Update branch `sfos4.2` from `master` for 0.3.0-3

---

.github/workflows/build-sfos3.1.yml
.github/workflows/build-sfos3.3.yml
.github/workflows/build-sfos4.2.yml

… documented at https://github.com/storeman-developers/harbour-storeman/wiki/Git-tag-format

Adapt to revised release tag naming scheme

---

rpm/harbour-storeman.spec

Ultimately fixes [issue 160 the supposedly proper way](https://github.com/storeman-developers/harbour-storeman/issues/160#issuecomment-1093024845).

Enhance spec file: pkgconfig(libsolv) & desktop-file-install

---

rpm/harbour-storeman.spec

See https://fedoraproject.org/wiki/Packaging_tricks#Recommended_values_for_the_Group:_tag

Switch to a standard `Group:`

---

qml/pages/AboutPage.qml
translations/harbour-storeman-cs.ts
translations/harbour-storeman-da.ts
translations/harbour-storeman-de.ts
translations/harbour-storeman-el.ts
translations/harbour-storeman-es.ts
translations/harbour-storeman-et.ts
translations/harbour-storeman-fi.ts
translations/harbour-storeman-fr.ts
translations/harbour-storeman-hu.ts
translations/harbour-storeman-it.ts
translations/harbour-storeman-nl.ts
translations/harbour-storeman-nl_BE.ts
translations/harbour-storeman-no.ts
translations/harbour-storeman-pl.ts
translations/harbour-storeman-pt.ts
translations/harbour-storeman-ru.ts
translations/harbour-storeman-sk.ts
translations/harbour-storeman-sl.ts
translations/harbour-storeman-sv.ts
translations/harbour-storeman-tt.ts
translations/harbour-storeman-zh.ts
translations/harbour-storeman.ts

… which was eliminated per PR #224.

Re-introduce Donations button

---

qml/pages/AboutPage.qml
translations/harbour-storeman-cs.ts
translations/harbour-storeman-da.ts
translations/harbour-storeman-de.ts
translations/harbour-storeman-el.ts
translations/harbour-storeman-es.ts
translations/harbour-storeman-et.ts
translations/harbour-storeman-fi.ts
translations/harbour-storeman-fr.ts
translations/harbour-storeman-hu.ts
translations/harbour-storeman-it.ts
translations/harbour-storeman-nl.ts
translations/harbour-storeman-nl_BE.ts
translations/harbour-storeman-no.ts
translations/harbour-storeman-pl.ts
translations/harbour-storeman-pt.ts
translations/harbour-storeman-ru.ts
translations/harbour-storeman-sk.ts
translations/harbour-storeman-sl.ts
translations/harbour-storeman-sv.ts
translations/harbour-storeman-tt.ts
translations/harbour-storeman-zh.ts
translations/harbour-storeman.ts

Re-introduce Donation button (#322)

Push final commit from devel→master for v0.3.1

---

harbour-storeman.pro
qml/pages/AboutPage.qml
rpm/harbour-storeman.spec

* [harbour-storeman.pro] Add 480x480 icon
* [AboutPage.qml] Increase icon size
* [spec file] Increase release: 0.3.1-2 → 0.3.1-3

[AboutPage.qml] Increase icon size (#341)

---

qml/harbour-storeman.qml
src/harbour-storeman.cpp

This resolves two of the many points listed at https://github.com/storeman-developers/harbour-storeman/issues/356

Enhance comments WRT Qt-ToDos

---

.github/workflows/build-sfos4.2_latest.yml

Reverts storeman-developers/harbour-storeman#389

Revert "Fix CI for sfos-latest"

---

rpm/harbour-storeman.changes
rpm/harbour-storeman.spec

Due to [this mishap](https://github.com/storeman-developers/harbour-storeman/pull/431#issuecomment-1664652911).

Prepare another release for 0.3.6

---

translations/harbour-storeman.ts

[harbour-storeman.ts] PRs #428 & #429 missed to adapt the base `.ts` file

---

LICENSE
README.md
qml/models/DevelopersModel.qml

* [README.md] Add Peter G. (nephros) to contributors
* [LICENSE] Add Peter G. (nephros) to contributors
* [DevelopersModel.qml] Add Peter G. (nephros) to contributors

`devel`→`master`: Add Peter G. (nephros) to contributors (#478)

---

rpm/harbour-storeman.changes
rpm/harbour-storeman.spec

Storeman is in well working beta state for years, reflect that by the version number.

Version increase to `0.7.0`

---

rpm/harbour-storeman.changes
rpm/harbour-storeman.spec

`devel`→`master`: Commits for v0.7.2-release**2**

---

rpm/harbour-storeman.changes
rpm/harbour-storeman.spec

Updates and supersedes PR #503.

[rpm/harbour-storeman.*] Init v0.7.3
